import "aos/dist/aos.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";
import Footer from "./common/Footer/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manrope",
});

const GeneralSansRegular = localFont({
  src: "../fonts/GeneralSans-Regular.otf",
  variable: "--font-general",
});

export const metadata: Metadata = {
  title: "Ena Ema Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${GeneralSansRegular.variable}`}
    >
      <body className="antialiased font-general">
        {children}
        <Footer />
      </body>
    </html>
  );
}
